/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./database.types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicCategoriesRowSchema = z.object({
  created_at: z.string().nullable(),
  default_amount: z.number().nullable(),
  household_id: z.string().nullable(),
  id: z.number(),
  name: z.string(),
  recurring: z.boolean(),
  type: z.string(),
});

export const publicCategoriesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  default_amount: z.number().optional().nullable(),
  household_id: z.string().optional().nullable(),
  id: z.number().optional(),
  name: z.string(),
  recurring: z.boolean().optional(),
  type: z.string(),
});

export const publicCategoriesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  default_amount: z.number().optional().nullable(),
  household_id: z.string().optional().nullable(),
  id: z.number().optional(),
  name: z.string().optional(),
  recurring: z.boolean().optional(),
  type: z.string().optional(),
});

export const publicCategoriesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("categories_household_id_fkey"),
    columns: z.tuple([z.literal("household_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("households"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicEmailTransactionsRowSchema = z.object({
  amount: z.number().nullable(),
  deleted_at: z.string().nullable(),
  from: z.string().nullable(),
  gmail_message_id: z.string().nullable(),
  household_id: z.string(),
  id: z.string(),
  merchant: z.string().nullable(),
  received_at: z.string(),
  transacted_at: z.string().nullable(),
});

export const publicEmailTransactionsInsertSchema = z.object({
  amount: z.number().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  from: z.string().optional().nullable(),
  gmail_message_id: z.string().optional().nullable(),
  household_id: z.string(),
  id: z.string().optional(),
  merchant: z.string().optional().nullable(),
  received_at: z.string().optional(),
  transacted_at: z.string().optional().nullable(),
});

export const publicEmailTransactionsUpdateSchema = z.object({
  amount: z.number().optional().nullable(),
  deleted_at: z.string().optional().nullable(),
  from: z.string().optional().nullable(),
  gmail_message_id: z.string().optional().nullable(),
  household_id: z.string().optional(),
  id: z.string().optional(),
  merchant: z.string().optional().nullable(),
  received_at: z.string().optional(),
  transacted_at: z.string().optional().nullable(),
});

export const publicEmailTransactionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("email_transactions_household_id_fkey"),
    columns: z.tuple([z.literal("household_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("households"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicHouseholdMembersRowSchema = z.object({
  household_id: z.string(),
  joined_at: z.string(),
  user_id: z.string(),
});

export const publicHouseholdMembersInsertSchema = z.object({
  household_id: z.string(),
  joined_at: z.string().optional(),
  user_id: z.string(),
});

export const publicHouseholdMembersUpdateSchema = z.object({
  household_id: z.string().optional(),
  joined_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicHouseholdMembersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("household_members_household_id_fkey"),
    columns: z.tuple([z.literal("household_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("households"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicHouseholdsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  name: z.string(),
});

export const publicHouseholdsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string(),
});

export const publicHouseholdsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
});

export const publicMerchantCategoryMappingsRowSchema = z.object({
  category_id: z.number(),
  created_at: z.string(),
  household_id: z.string(),
  id: z.number(),
  merchant: z.string(),
  updated_at: z.string(),
});

export const publicMerchantCategoryMappingsInsertSchema = z.object({
  category_id: z.number(),
  created_at: z.string().optional(),
  household_id: z.string(),
  id: z.number().optional(),
  merchant: z.string(),
  updated_at: z.string().optional(),
});

export const publicMerchantCategoryMappingsUpdateSchema = z.object({
  category_id: z.number().optional(),
  created_at: z.string().optional(),
  household_id: z.string().optional(),
  id: z.number().optional(),
  merchant: z.string().optional(),
  updated_at: z.string().optional(),
});

export const publicMerchantCategoryMappingsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("merchant_category_mappings_category_id_fkey"),
    columns: z.tuple([z.literal("category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("merchant_category_mappings_household_id_fkey"),
    columns: z.tuple([z.literal("household_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("households"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicTransactionsRowSchema = z.object({
  amount: z.number(),
  category_id: z.number().nullable(),
  created_at: z.string(),
  date: z.string(),
  description: z.string().nullable(),
  household_id: z.string().nullable(),
  id: z.number(),
  public_id: z.string(),
  via: z.string().nullable(),
});

export const publicTransactionsInsertSchema = z.object({
  amount: z.number(),
  category_id: z.number().optional().nullable(),
  created_at: z.string().optional(),
  date: z.string().optional(),
  description: z.string().optional().nullable(),
  household_id: z.string().optional().nullable(),
  id: z.number().optional(),
  public_id: z.string().optional(),
  via: z.string().optional().nullable(),
});

export const publicTransactionsUpdateSchema = z.object({
  amount: z.number().optional(),
  category_id: z.number().optional().nullable(),
  created_at: z.string().optional(),
  date: z.string().optional(),
  description: z.string().optional().nullable(),
  household_id: z.string().optional().nullable(),
  id: z.number().optional(),
  public_id: z.string().optional(),
  via: z.string().optional().nullable(),
});

export const publicTransactionsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("transactions_category_id_fkey"),
    columns: z.tuple([z.literal("category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("transactions_household_id_fkey"),
    columns: z.tuple([z.literal("household_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("households"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const publicUserOauthTokensRowSchema = z.object({
  last_history_id: z.string().nullable(),
  refresh_token: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});

export const publicUserOauthTokensInsertSchema = z.object({
  last_history_id: z.string().optional().nullable(),
  refresh_token: z.string(),
  updated_at: z.string().optional(),
  user_id: z.string(),
});

export const publicUserOauthTokensUpdateSchema = z.object({
  last_history_id: z.string().optional().nullable(),
  refresh_token: z.string().optional(),
  updated_at: z.string().optional(),
  user_id: z.string().optional(),
});

export const publicCreateHouseholdArgsSchema = z.object({
  household_name: z.string(),
});

export const publicCreateHouseholdReturnsSchema = z.string();

export const publicJoinHouseholdArgsSchema = z.object({
  target_household_id: z.string(),
});

export const publicJoinHouseholdReturnsSchema = z.undefined();

export const publicMyHouseholdIdsArgsSchema = z.never();

export const publicMyHouseholdIdsReturnsSchema = z.array(z.string());
